### ISSUE TITLE
Create Index on multiple columns?

### ISSUE THREAD

**Issue by inawlaljar** [yahoo/squidb#101]
Is it possible to create index on multiple columns?

for e.g. 
tryCreateIndex(User.TABLE.index("ss_fb_def_item_idx", [User.ADDRESS_ID, User.ORG_ID, User.EDUCATION_ID]));

**Comment by jdkoren** [comment]
Sure you can. The [`Table.index()`](https://github.com/yahoo/squidb/blob/master/squidb/src/com/yahoo/squidb/sql/Table.java#L61) method (and the Index constructor) accepts a variable number of `Property<?>` objects. You can write it like this:
```java
User.TABLE.index("ss_fb_def_item_idx", User.ADDRESS_ID, User.ORG_ID, User.EDUCATION_ID)
```
You could also declare an array if you wanted to since var-args can accept an array.

**Comment by inawlaljar** [comment]
THanks.
