### ISSUE TITLE
Object Hierarchy

### ISSUE THREAD

**Issue by inawlaljar** [yahoo/squidb#102]
Hi, 

I have an object hierarchy.. for e.g.

User has many Addresses 
Class User{
   ArrayList <Address> address;
}

Will the save in User... "db.persist(user)" will save all addresses? if not, what is the best approach? 
Thanks,
Raj

**Comment by sbosley** [comment]
If Address is also a table model, the answer is no. SquiDB isn't an ORM and does not manage object relationships, which is by design. You can see [this wiki page](https://github.com/yahoo/squidb/wiki/Defining-table-schemas#squidb-is-not-an-orm) or [this issue](https://github.com/yahoo/squidb/issues/38) for more information.

How you want to manage relations is entirely up to you! There's no single best strategy, although that wiki page and the discussion in the issue offer various options.

If Address is not another table but rather e.g. a serializable POJO, you may be able to use the jackson plugin to store the list as a serialized String -- let us know if this is your use case and we can provide more info.

**Comment by sbosley** [comment]
I'm assuming this question has been answered since there hasn't been additional activity -- feel free to reply if there are more questions though!
