### ISSUE TITLE
Eclipse Support

### ISSUE THREAD

**Issue by bleuf1sh** [yahoo/squidb#115]
Would it be possible to add instructions for how to setup squidb for use in an Android Eclipse project to the Wiki? -Thanks

**Comment by sbosley** [comment]
I'm not sure how to best advise you on this one -- are you using gradle? Build systems other than gradle aren't officially supported I'm afraid, nor do we have plans to add support for anything else at this time. If you are using gradle (e.g. the Eclipse Gradle plugin), the instructions on [this wiki page](https://github.com/yahoo/squidb/wiki/Adding-SquiDB-as-a-dependency) should still work. 

If you are not using gradle, your best bet is probably to download jars from Bintray and manually add them to your project ([here's our Bintray page](https://bintray.com/yahoo/maven/squidb/view)). Or, you could clone SquiDB and import the projects as source dependencies. You can configure APT for code generation in eclipse using the instructions found [here](https://www.eclipse.org/jdt/apt/introToAPT.php).

Since things other than gradle aren't officially supported I'm not sure if the ideas for non-gradle will be sufficient -- they might be though! If you find out more info that you think will be helpful to future visitors, you're welcome to post your findings back here and I'll link to this issue from a wiki page.

**Comment by bleuf1sh** [comment]
@sbosley  thanks! I'll try those out and if something works out smoothly I'll let you know. I appreciate the quick response and I really loved y'alls talk at Droidcon Tel Aviv.

**Comment by sbosley** [comment]
Closing this issue as we still have no plans to support non-gradle build systems. @bleuf1sh not sure if you found a solution that works for you, but if you did feel free to share details and we'll add a note to the wiki.
