### ISSUE TITLE
Change default id name

### ISSUE THREAD

**Issue by Leland-Takamine** [yahoo/squidb#27]
I have some pre-populated sqlite databases that I'd like to access via squidb. The id columns on all of my tables are named "id" (not "_id"). I'd like to be able to change the default id name in squidb to "id" for this reason.

**Comment by sbosley** [comment]
Hmm I'm going to have to think about this...originally we didn't want to allow changing that constant for best compatibility with Android's [CursorAdapter](https://developer.android.com/reference/android/widget/CursorAdapter.html), which requires the "_id" name. I'll have to think through the implications of adding an api to change what was designed to be a compile time constant a bit more.

Two options in the meantime:
 * Write a migration to [rename your id columns](http://stackoverflow.com/questions/805363/how-do-i-rename-a-column-in-a-sqlite-database-table). Since I don't know yet whether or not changing the id column name will be feasible or high priority on our roadmap, this is the option I'd recommend if you're willing.
 * Clone SquiDB and manually change the constant in the code (as you probably already know it's in TableModel). You'd have to build from source, but in theory this would "just work".

**Comment by sbosley** [comment]
The ability to specify a custom name for primary keys was added in #37. [Here's an example](https://github.com/yahoo/squidb/wiki/Defining-table-schemas#custom-primary-key-definitions) on the wiki of how to use the new annotation. You should now be able to define model specs with your legacy column name without needing to clone squidb or write a migration to a different name!

The relevant code has been merged into SquiDB master and will be included in our upcoming 1.0.1 release.
