### ISSUE TITLE
the old database SQLite compatibility

### ISSUE THREAD

**Issue by kamilwlf** [yahoo/squidb#28]
Does your library will be compatible with SQLite? Can I normally use it with my old SQLite database without any modification?

I ask because I have in the production app with traditional  SQLite database with many lines of code and of course I have no way to remove these pieces of code.

I would like to add a new code(using your library) but not delete the old one.

**Comment by sbosley** [comment]
You will almost certainly need to modify at least some of your production code in order to be able to effectively use the library. That being said, it's probably still doable. 

One caveat up front: at this time, SquiDB only supports integer primary keys. If you use non-integer primary keys, you will probably have some difficulty using the library. We may remove this limitation in a future release, but don't have an ETA to share right now.

The first thing you'd need to do is [define model specs](https://github.com/yahoo/squidb/wiki/Defining-table-schemas) for your table schemas. This will enable the code generator to generate model classes that you can work with in your [AbstractDatabase subclass and DatabaseDao](https://github.com/yahoo/squidb/wiki/Setting-up-a-database-for-your-app).

Our AbstractDatabase class is a wrapper around SQLiteOpenHelper. You will at minimum need to replace instances of SQLiteOpenHelper/SQLiteDatabase with a subclass of AbstractDatabase, since having more than one instance of SQLiteOpenHelper can lead to bad synchronization problems (see [this StackOverflow post](http://stackoverflow.com/questions/8888530/is-it-ok-to-have-one-instance-of-sqliteopenhelper-shared-by-all-activities-in-an) for more info).

Much of your production code could probably use a singleton instance of your AbstractDatabase subclass in place of calls to SQLiteDatabase. However, you wouldn't be getting many of the benefits of the library, since it's DatabaseDao that does the work of translating between model classes and SQL, ensuring type safety, etc. -- and the apis that DatabaseDao offers are different from those offered by SQLiteDatabase. They're a pretty simple wrapper, so it's all the same SQL under the hood, but it's not a drop in replacement. Furthermore, not all of the SQLiteDatabase apis are available via AbstractDatabase, so you'd probably need to update at least a few calls. Technically you could expose the underlying SQLiteDatabase from your AbstractDatabase subclass and call it directly, but I'd definitely recommend doing that as little as possible and phasing it out as soon as you could update your production code.

I think that the library would be much more useful to you if you updated your production code to use it fully. That being said, you could probably do it step by step and phase out old code over time, rather than immediately if you really wanted to.

Hope that answers your question!

**Comment by sbosley** [comment]
I'm going to assume the lack of activity on this issue means it's resolved. Feel free to reopen it if there are any further questions!
