### ISSUE TITLE
Are there any helper functions for managing relations?

### ISSUE THREAD

**Issue by MFlisar** [yahoo/squidb#31]
Like having a person and books... And I want to get all the books of this person. Can I only write a `ModelMethod` that returns all books? Or is there some mechanism that I haven't found yet?

If not, creating such functions with an annotation and caching the result in a local variable would be a nice improvement...

**Comment by sbosley** [comment]
One could envision writing a model method like this to do some caching:

```java
@ModelMethod
public static List<Book> getBooks(Person instance, DatabaseDao dao) {
    if (instance.hasTransitory(CACHED_BOOKS_KEY)) {
        return (List<Book>) instance.getTransitory(CACHED_BOOKS_KEY);
    }
    SquidCursor<Book> books = dao.query(Book.class, Query.select(Book.PROPERTIES)
        .where(Book.PERSON_ID.eq(instance.getId()));
    // You'd have to implement this helper to iterate through the cursor
    List<Books> booksList = cursorToList(books); 
    person.setTransitory(CACHED_BOOKS_KEY, books);
    return booksList;
}
```

However, I would advise extreme caution if you go this route. There's no mechanism to invalidate the cache (unless you want to do something fancy with [UriNotifier](https://github.com/yahoo/squidb/wiki/Listening-for-data-changes-with-UriNotifier)). What you're asking for is more of an ORM feature, and SquiDB isn't really an ORM--which is actually by design. SquiDB's philosophy is to make it easier to work with SQL and the Android SQL APIs, not to hide them from you entirely. We've found that true ORMs that hide the underlying SQL to focus on object relationships tend to be difficult to reason about and have unpredictable performance characteristics, so I think it's unlikely that we'll introduce any features that manage high level relationships.

Usually when I'm thinking about object relationships I try to consider if there's a way to get the data I want at the app level using a join query and some clever use of group_concat. 9 times out of 10 there is.
