### ISSUE TITLE
Protocol Buffers support.

### ISSUE THREAD

**Issue by clertonleal** [yahoo/squidb#35]

**Comment by sbosley** [comment]
Can you elaborate on what you're asking for with this feature request? Just the ability to serialize model objects using protobuf, or something more?

**Comment by clertonleal** [comment]
Sorry for the lack of detail.
I love Protocol Buffers, and I love the ability to generate entities in different languages using a simple .proto file.
How can I generate and evolve my entities with .proto files and continue using Squidb annotations? It is possible?
It will be necessary to implement a specific Protocol Buffers compiler for Squidb or there is another simple solution?

**Comment by sbosley** [comment]
I've thought about this a bit more over the past month. I think it would be necessary to implement a specific protocol buffers compiler, or perhaps use an approach like GreenDAO uses that runs a separate program to convert in-memory protobuf objects into table schemas (which unfortunately loses some of the ease-of-use of the compile-time annotation processing approach). 

However, I don't think this is a direction that we'll be going. From what I understand, protobuf entities are relational (entities can refer to other entities), which is not the case with squidb models (which are just a simple way to specify table schemas). If you or anyone else in the community wanted to give it a shot, we'd be happy to look at anything you came up with! I think though that we're going to continue to invest in making our model specs more powerful/flexible rather than trying to support many different entity definition schemes.
