### ISSUE TITLE
Improvement of documentation for Model usage

### ISSUE THREAD

**Issue by aercanozcan** [yahoo/squidb#38]
It clearly shows how to use single model but it does not show that is it possible to use a model inside a model or is it possible to define one to many by using Lists.

for example:
```
class Car{

List <Tire> tires

}

class Tire {
double pressure;
String position;
}
```

**Comment by sbosley** [comment]
In SquiDB, all model specs are defined separately. That is because SquiDB is not an ORM, which is actually by design, so it doesn't do anything special to manage your object relationships. We have found that ORMs that attempt to manage object relationships and hide the underlying SQL tend to be difficult to reason about or have unpredictable performance characteristics. Because of that, SquiDB focuses instead on making it easy to work with SQL--not hiding it from you.

To define a relationship like the one you're describing, I imagine you'd use some kind of foreign key constraint in the Tire spec:

```java
@TableModelSpec(className = "Tire", tableName = "tires", 
    tableConstraint = "FOREIGN KEY(carId) REFERENCES cars(_id)")
TireSpec {
    long carId;
    double pressure;
    String position;
}
```

Think of your models as a combination of table schema and helpers for CRUD operations, rather than relational objects. How you write the SQL and work with your tables to maintain relationships is entirely up to you! SquiDB gives you the freedom to use any strategy you want. You can check out the comment in issue #31 for one possible strategy--it sounds like what you're asking for, although it's not the strategy I would use personally.

We've had similar questions enough times though that I will add to the wiki clarifying what SquiDB does and doesn't do :) Thanks for opening the issue, hope that answers your question!

**Comment by jdkoren** [comment]
There is an option to use the `squidb-jackson` plugin to store a List of tires in the cars table. This isn't a relationship though as there's no tires table (you wouldn't be able to query for tires, for example). Let us know if you'd like more information about that.
