### ISSUE TITLE
Troubleshooting / ProGuard rules needed?

### ISSUE THREAD

**Issue by dotWee** [yahoo/squidb#72]
After a fresh and clean gradle build, the assemble process stoped working.

I'm getting `Warning: Encountered ErrorType accumulating imports` followed by `Error:(x, y) error: cannot find symbol class (Model Name)` for each usage of those models.

Model objects are still generated and accessible. It just seems those generated classes aren't visible for the compiler. I'm using the lastest *Java 7 JDK (u80)* with *squidb 1.1.0*, *Gradle 2.5* and *Android Plugin 1.3.0*.

Any ideas what could cause those errors?

**Comment by sbosley** [comment]
Well, the "Warning: Encountered ErrorType accumulating imports" is actually pretty normal when you're defining a model spec for a view or using ModelMethod. It happens because such specs typically refer to model code that hasn't been generated yet, which should actually be ok. (If you're not referring to a generated model class from within any of your spec files, then something else might be amiss in one of your spec classes).

I have noticed though (at least in my own projects) that the "cannot find symbol" errors will sometimes occur when there's some other compilation error in the project--it seems like for some reason, sometimes when there are other compile errors the code generation process goes awry. Finding and fixing those other errors often fixes that problem for me.

Was there a stable commit from before you did the clean build that you can revert to and test if a clean build works there? If a clean build works on an older commit that could help narrow it down to any changes introduced recently.

FWIW, I bumped my own gradle version and android plugins to the versions you were using and I couldn't reproduce the error even with a clean build, so I don't think it's a plugin compatibility issue.

**Comment by dotWee** [comment]
Thanks for your response. I went through my last commits and discovered a typo, I've set a column spec to the default integer 0800 instead of 8000. Since all values are bracketed, Intellij couldn't refer me on that. Thanks again!

**Comment by sbosley** [comment]
Great! Glad the issue was resolved.
