### ISSUE TITLE
How to create the db?

### ISSUE THREAD

**Issue by inawlaljar** [yahoo/squidb#98]
I have upgraded to Squidb 2.0. Now when I try to create the db object (class that extends SquidDatabase), it doesn't create the database.

Do I need to call any method? My understanding was that on Object create, it creates a db.

Please suggest.

Thanks,

**Comment by jdkoren** [comment]
On Android, the actual database file is created the first time you try to actually open it. The same is true for SquiDB (because it uses Android's `SQLiteOpenHelper` underneath). This should happen the first time you run any database operation, like a query.

If you want, you can open it explicitly by calling `squidDatabase.getDatabase()`, but usually this isn't necessary.

**Comment by sbosley** [comment]
Seems like this was resolved -- closing.
